[0m09:34:29.455471 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250DA4D6900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250DA4D76E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250DA4D7620>]}


============================== 09:34:29.492761 | c2273a31-5fb4-450f-8899-7a953c2f974e ==============================
[0m09:34:29.492761 [info ] [MainThread]: Running with dbt=1.9.4
[0m09:34:29.494666 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\DELL\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m09:35:37.394613 [debug] [MainThread]: Starter project path: C:\Users\DELL\env\Lib\site-packages\dbt\include\starter_project
[0m09:35:37.429737 [info ] [MainThread]: 
Your new dbt project "semi" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:35:37.434638 [info ] [MainThread]: Setting up your profile.
[0m09:36:43.728619 [info ] [MainThread]: Profile semi written to C:\Users\DELL\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m09:36:43.737809 [debug] [MainThread]: Command `dbt init` succeeded at 09:36:43.737809 after 134.52 seconds
[0m09:36:43.738893 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250D70A6720>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250D70A7F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250DA4D7620>]}
[0m09:36:43.741283 [debug] [MainThread]: Flushing usage events
[0m09:36:45.418280 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:37:47.501801 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F1E51E690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F22242CF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F22240530>]}


============================== 09:37:47.508269 | 5f2c314b-8211-451a-a1ba-9f9fdacb0e65 ==============================
[0m09:37:47.508269 [info ] [MainThread]: Running with dbt=1.9.4
[0m09:37:47.508269 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\DELL\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m09:37:47.563796 [info ] [MainThread]: dbt version: 1.9.4
[0m09:37:47.566015 [info ] [MainThread]: python version: 3.12.10
[0m09:37:47.568161 [info ] [MainThread]: python path: C:\Users\DELL\env\Scripts\python.exe
[0m09:37:47.569809 [info ] [MainThread]: os info: Windows-11-10.0.22621-SP0
[0m09:38:08.230376 [info ] [MainThread]: Using profiles dir at C:\Users\DELL\.dbt
[0m09:38:08.232284 [info ] [MainThread]: Using profiles.yml file at C:\Users\DELL\.dbt\profiles.yml
[0m09:38:08.233987 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\DELL\semigod_socials\dbt_project.yml
[0m09:38:08.235599 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m09:38:08.237825 [debug] [MainThread]: Command `dbt debug` failed at 09:38:08.237825 after 21.00 seconds
[0m09:38:08.243088 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F1E51E690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F22872660>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F36A25340>]}
[0m09:38:08.247082 [debug] [MainThread]: Flushing usage events
[0m09:38:09.796446 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:39:10.232761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED6C340A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED6FF41D00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED6FF40530>]}


============================== 09:39:10.234807 | 82613a33-fdb5-4eed-935f-2873cf80e84e ==============================
[0m09:39:10.234807 [info ] [MainThread]: Running with dbt=1.9.4
[0m09:39:10.234807 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\DELL\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m09:39:10.276557 [info ] [MainThread]: dbt version: 1.9.4
[0m09:39:10.280593 [info ] [MainThread]: python version: 3.12.10
[0m09:39:10.280593 [info ] [MainThread]: python path: C:\Users\DELL\env\Scripts\python.exe
[0m09:39:10.283854 [info ] [MainThread]: os info: Windows-11-10.0.22621-SP0
[0m09:39:15.291415 [info ] [MainThread]: Using profiles dir at C:\Users\DELL\.dbt
[0m09:39:15.298819 [info ] [MainThread]: Using profiles.yml file at C:\Users\DELL\.dbt\profiles.yml
[0m09:39:15.300193 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\DELL\semigod_socials\dbt_project.yml
[0m09:39:15.300759 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m09:39:15.301713 [debug] [MainThread]: Command `dbt debug` failed at 09:39:15.301713 after 5.27 seconds
[0m09:39:15.301713 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED6FED6900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED84071820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ED8448DBB0>]}
[0m09:39:15.301713 [debug] [MainThread]: Flushing usage events
[0m09:39:16.767946 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m09:40:16.037016 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3B040AA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3DE8F9E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3DE8C950>]}


============================== 09:40:16.044592 | d5c79319-8ee8-4389-b9b1-4035545dafe5 ==============================
[0m09:40:16.044592 [info ] [MainThread]: Running with dbt=1.9.4
[0m09:40:16.044592 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\DELL\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:40:16.114980 [info ] [MainThread]: dbt version: 1.9.4
[0m09:40:16.125377 [info ] [MainThread]: python version: 3.12.10
[0m09:40:16.125377 [info ] [MainThread]: python path: C:\Users\DELL\env\Scripts\python.exe
[0m09:40:16.128291 [info ] [MainThread]: os info: Windows-11-10.0.22621-SP0
[0m09:40:20.808208 [info ] [MainThread]: Using profiles dir at C:\Users\DELL\.dbt
[0m09:40:20.808208 [info ] [MainThread]: Using profiles.yml file at C:\Users\DELL\.dbt\profiles.yml
[0m09:40:20.808208 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\DELL\semigod_socials\dbt_project.yml
[0m09:40:20.808208 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m09:40:20.819609 [debug] [MainThread]: Command `dbt debug` failed at 09:40:20.819609 after 5.01 seconds
[0m09:40:20.820151 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F3DE370E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F534ECF80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020F52C73F80>]}
[0m09:40:20.820151 [debug] [MainThread]: Flushing usage events
[0m09:40:22.305412 [debug] [MainThread]: An error was encountered while trying to flush usage events
